### ISSUE TITLE
Link save button to add graph

### ISSUE THREAD

**Issue by Sid-the-Slothh** [H-SM/GraphPathGuru#50]
The save button needs to be linked to the addgraph mongo API call. But there need to be some checks and balances to make sure that the data to be pushed to the database without any missing data dependencies. It should look something like this:
(req, res) => {
    // ensure graph is saved to input.txt
    // insure backend algorithm is saved in output.txt, and <result> is properly extracted
    // insure the graph name is unique (if not provided, generate the boilerplate unique name)
    // favourite is by default False
    .
    .
    // Do the push to mongo here
}
Do point out any flaws in this approach @H-SM @ThapaVinay

**Comment by H-SM** [comment]
completed over on this PR #60. If you feel like there need to be any further changes over it, we could reopen the issue again...

happy coding... 🚀
